### ISSUE TITLE
httpS proxy segfault

### ISSUE THREAD

**Issue by whoizit** [nadoo/glider#128]
`glider -verbose -listen http://proxy:password@:10618`
I specify http**s** proxy in SwitchyOmega proxy plugin for Firefox
![image_2019-10-21_09-08-20](https://user-images.githubusercontent.com/359276/67180509-8588bc00-f3e2-11e9-9e22-efb9991a6eab.png)

```
2019/10/21 02:02:50 strategy.go:82: [strategy] forward to remote servers in round robin mode.
2019/10/21 02:02:50 ipset_linux.go:83: protocol not supported
2019/10/21 02:02:50 server.go:31: [http] listening TCP on :10618
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x535d0d]

goroutine 9 [running]:
github.com/nadoo/glider/proxy/http.(*HTTP).servRequest(0xc0000563c0, 0x0, 0xc00000e600)
        /home/user/.go/src/github.com/nadoo/glider/proxy/http/server.go:74 +0xbd
github.com/nadoo/glider/proxy/http.(*HTTP).Serve(0xc0000563c0, 0x78fbe0, 0xc000010088)
        /home/user/.go/src/github.com/nadoo/glider/proxy/http/server.go:68 +0x33d
created by github.com/nadoo/glider/proxy/http.(*HTTP).ListenAndServe
        /home/user/.go/src/github.com/nadoo/glider/proxy/http/server.go:40 +0x25a
```

**Comment by nadoo** [comment]
Thanks for your report, `https proxy` in SwitchyOmega = `http over tls proxy`, you should use http instead.

**Comment by whoizit** [comment]
http proxy running:
```
glider -verbose -listen http://proxy:Gzrm3yuMECPDCcE2w8sjSkwNYaoANXjjRhG26S74Lz6YP4bS3t@[202:9877:2815:cd91:336:2a16:bfd9:7258]:10618
2019/10/21 02:46:57 strategy.go:82: [strategy] forward to remote servers in round robin mode.
2019/10/21 02:46:57 ipset_linux.go:83: protocol not supported
2019/10/21 02:46:57 server.go:31: [http] listening TCP on [202:9877:2815:cd91:336:2a16:bfd9:7258]:10618
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x535d0d]

goroutine 9 [running]:
github.com/nadoo/glider/proxy/http.(*HTTP).servRequest(0xc0000563c0, 0x0, 0xc00000e600)
        /home/user/.go/src/github.com/nadoo/glider/proxy/http/server.go:74 +0xbd
github.com/nadoo/glider/proxy/http.(*HTTP).Serve(0xc0000563c0, 0x78fbe0, 0xc000010088)
        /home/user/.go/src/github.com/nadoo/glider/proxy/http/server.go:68 +0x33d
created by github.com/nadoo/glider/proxy/http.(*HTTP).ListenAndServe
        /home/user/.go/src/github.com/nadoo/glider/proxy/http/server.go:40 +0x25a
```
trying to connect as socks5 proxy
`$ curl -v -x socks5://proxy:Gzrm3yuMECPDCcE2w8sjSkwNYaoANXjjRhG26S74Lz6YP4bS3t@[202:9877:2815:cd91:336:2a16:bfd9:7258]:10618 http://iplocation.net`

**Comment by nadoo** [comment]
You should set protocol to `HTTP` in SwitchyOmega, and I'll fix the panic later.

**Comment by whoizit** [comment]
fixed
