### ISSUE TITLE
tls cannot run in version 0.9.2

### ISSUE THREAD

**Issue by nic8888dsf** [nadoo/glider#148]
glider.exe -listen tls://:4453?cert=ca.crt^&key=ca.key,socks5:// -verbose
2020/01/27 22:29:22 strategy.go:82: [strategy] forward to remote servers in round robin mode.
2020/01/27 22:29:22 tls.go:135: [tls] listening TCP on :4453 with TLS
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x525d09]

goroutine 7 [running]:
github.com/nadoo/glider/common/conn.(*Conn).Read(0x0, 0xc00012e360, 0x2, 0x103, 0xc000143c78, 0x40a05c, 0x6d4da0)
        /home/runner/work/glider/glider/common/conn/conn.go:30 +0x29
io.ReadAtLeast(0x780320, 0x0, 0xc00012e360, 0x2, 0x103, 0x2, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.13.3/x64/src/io/io.go:310 +0x8e
io.ReadFull(...)
        /opt/hostedtoolcache/go/1.13.3/x64/src/io/io.go:329
github.com/nadoo/glider/proxy/socks5.(*Socks5).handshake(0xc0001202d0, 0x782480, 0x0, 0x41775b, 0x1a5a300, 0x203000000000000, 0x1a6ffff, 0x1cc7d0)
        /home/runner/work/glider/glider/proxy/socks5/socks5.go:434 +0xd2
github.com/nadoo/glider/proxy/socks5.(*Socks5).Serve(0xc0001202d0, 0x787120, 0xc000146000)
        /home/runner/work/glider/glider/proxy/socks5/socks5.go:118 +0xeb
github.com/nadoo/glider/proxy/tls.(*TLS).Serve(0xc000108000, 0x787540, 0xc000006070)
        /home/runner/work/glider/glider/proxy/tls/tls.go:155 +0xb0
created by github.com/nadoo/glider/proxy/tls.(*TLS).ListenAndServe
        /home/runner/work/glider/glider/proxy/tls/tls.go:144 +0x261

**Comment by nic8888dsf** [comment]
socks5.go 

func (s *Socks5) Serve(cc net.Conn) {
	defer cc.Close()

	var c *conn.Conn
	switch ccc := cc.(type) {
	case *net.TCPConn:
		ccc.SetKeepAlive(true)
		c = conn.NewConn(ccc)
	case *conn.Conn:
		c = ccc
	case *tls.Conn:
		c = conn.NewConn(ccc)
	}
