### ISSUE TITLE
glider crashes when latest version of ss-android connects

### ISSUE THREAD

**Issue by felixonmars** [nadoo/glider#29]
```
Jul 06 18:15:48 nonexist.felixc.at glider[943]: panic: chacha20poly1305: invalid buffer overlap
Jul 06 18:15:48 nonexist.felixc.at glider[943]: goroutine 9 [running]:
Jul 06 18:15:48 nonexist.felixc.at glider[943]: golang.org/x/crypto/chacha20poly1305.(*chacha20poly1305).openGeneric(0xc420018260, 0xc42010e000, 0x0, 0x10000, 0x55cdf98c1e20, 0xc, 0x80, 0xc42010e020, 0x39, 0xffe0, ...)
Jul 06 18:15:48 nonexist.felixc.at glider[943]:         /build/glider/src/.gopath/src/golang.org/x/crypto/chacha20poly1305/chacha20poly1305_generic.go:70 +0x72a
Jul 06 18:15:48 nonexist.felixc.at glider[943]: golang.org/x/crypto/chacha20poly1305.(*chacha20poly1305).open(0xc420018260, 0xc42010e000, 0x0, 0x10000, 0x55cdf98c1e20, 0xc, 0x80, 0xc42010e020, 0x39, 0xffe0, ...)
Jul 06 18:15:48 nonexist.felixc.at glider[943]:         /build/glider/src/.gopath/src/golang.org/x/crypto/chacha20poly1305/chacha20poly1305_amd64.go:68 +0x462
Jul 06 18:15:48 nonexist.felixc.at glider[943]: golang.org/x/crypto/chacha20poly1305.(*chacha20poly1305).Open(0xc420018260, 0xc42010e000, 0x0, 0x10000, 0x55cdf98c1e20, 0xc, 0x80, 0xc42010e020, 0x39, 0xffe0, ...)
Jul 06 18:15:48 nonexist.felixc.at glider[943]:         /build/glider/src/.gopath/src/golang.org/x/crypto/chacha20poly1305/chacha20poly1305.go:75 +0x105
Jul 06 18:15:48 nonexist.felixc.at glider[943]: github.com/shadowsocks/go-shadowsocks2/shadowaead.Unpack(0xc42010e000, 0x10000, 0x10000, 0xc42010e000, 0x59, 0x10000, 0x55cdf9798fa0, 0xc420054440, 0x0, 0xc420040db8, ...)
Jul 06 18:15:48 nonexist.felixc.at glider[943]:         /build/glider/src/.gopath/src/github.com/shadowsocks/go-shadowsocks2/shadowaead/packet.go:56 +0x227
Jul 06 18:15:48 nonexist.felixc.at glider[943]: github.com/shadowsocks/go-shadowsocks2/shadowaead.(*packetConn).ReadFrom(0xc420054440, 0xc42010e000, 0x10000, 0x10000, 0x10000, 0x10000, 0xc420031400, 0x1, 0x7fdebde2b000)
Jul 06 18:15:48 nonexist.felixc.at glider[943]:         /build/glider/src/.gopath/src/github.com/shadowsocks/go-shadowsocks2/shadowaead/packet.go:91 +0xee
Jul 06 18:15:48 nonexist.felixc.at glider[943]: github.com/nadoo/glider/proxy/ss.(*PktConn).ReadFrom(0xc420054480, 0xc4200fe000, 0x10000, 0x10000, 0x10000, 0x10000, 0x0, 0x0, 0x0)
Jul 06 18:15:48 nonexist.felixc.at glider[943]:         /build/glider/src/.gopath/src/github.com/nadoo/glider/proxy/ss/packet.go:36 +0xad
Jul 06 18:15:48 nonexist.felixc.at glider[943]: github.com/nadoo/glider/proxy/ss.(*SS).ListenAndServeUDP(0xc4200108d0)
Jul 06 18:15:48 nonexist.felixc.at glider[943]:         /build/glider/src/.gopath/src/github.com/nadoo/glider/proxy/ss/ss.go:190 +0x2e3
Jul 06 18:15:48 nonexist.felixc.at glider[943]: created by github.com/nadoo/glider/proxy/ss.(*SS).ListenAndServe
Jul 06 18:15:48 nonexist.felixc.at glider[943]:         /build/glider/src/.gopath/src/github.com/nadoo/glider/proxy/ss/ss.go:73 +0x41
```

**Comment by nadoo** [comment]
Did you compile it with go 1.11？

**Comment by felixonmars** [comment]
It was compiled with go 1.10.3

**Comment by nadoo** [comment]
That was caused by this update: https://github.com/golang/crypto/commit/37a17fe027db43f76fd88b056ddf588563fc8722#diff-91f6681e8c135c030e318609a90724a8, in the line 59, and go-ss2 lib hasn't update yet, so there will be a panic.

I'll use go vendor to keep dependencies more stable, and upload new binaries.

**Comment by felixonmars** [comment]
Thanks, updated to 0.6.1.
