### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference (mipsle)

### ISSUE THREAD

**Issue by wxyzh** [nadoo/glider#32]
I'm using glider in ubnt er-x mipsle
run` glider -listen http://:1085`
output 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x1398cc]

goroutine 1 [running]:
net/url.(*Userinfo).Username(...)
 /home/xxx/.gvm/gos/go1.9.7/src/net/url/url.go:370
github.com/nadoo/glider/proxy/http.NewHTTP(0x7fc84a8a, 0xc, 0x342de0, 0x8c88050, 0x4, 0x7fc84a8a, 0x8c00a80)
/home/xxx/.gvm/pkgsets/go1.9.7/global/src/github.com/nadoo/glider/proxy/http/http.go:46 +0x150
github.com/nadoo/glider/proxy/http.NewHTTPServer(0x7fc84a8a, 0xc, 0x342de0, 0x8c88050, 0x8c00acc, 0x8c72501, 0x0, 0x4)     /home/xxx/.gvm/pkgsets/go1.9.7/global/src/github.com/nadoo/glider/proxy/http/http.go:66 +0x54
github.com/nadoo/glider/proxy.ServerFromURL(0x7fc84a8a, 0xc, 0x342de0, 0x8c88050, 0x0, 0x8c4a0c0, 0x0, 0x0)
/home/xxx/.gvm/pkgsets/go1.9.7/global/src/github.com/nadoo/glider/proxy/server.go:47 +0x2f0
main.main()
/home/xxx/.gvm/pkgsets/go1.9.7/global/src/github.com/nadoo/glider/main.go:84 +0x494
```

and run` glider -listen socks5://:1085`

output

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x13ea90]

goroutine 1 [running]:
net/url.(*Userinfo).Username(...)
/home/xxx/.gvm/gos/go1.9.7/src/net/url/url.go:370
github.com/nadoo/glider/proxy/socks5.NewSOCKS5(0x7f821a88, 0xe, 0x342de0, 0x8d88050, 0x6, 0x7f821a88, 0x8d00a80)
 /home/xxx/.gvm/pkgsets/go1.9.7/global/src/github.com/nadoo/glider/proxy/socks5/socks5.go:55 +0x150
github.com/nadoo/glider/proxy/socks5.NewSocks5Server(0x7f821a88, 0xe, 0x342de0, 0x8d88050, 0x8d00ad0, 0x8d72401, 0x0, 0x3)
/home/xxx/.gvm/pkgsets/go1.9.7/global/src/github.com/nadoo/glider/proxy/socks5/socks5.go:75 +0x54
github.com/nadoo/glider/proxy.ServerFromURL(0x7f821a88, 0xe, 0x342de0, 0x8d88050, 0x0, 0x8d4a0c0, 0x0, 0x0)
/home/xxx/.gvm/pkgsets/go1.9.7/global/src/github.com/nadoo/glider/proxy/server.go:47 +0x2f0
main.main()
 /home/xxx/.gvm/pkgsets/go1.9.7/global/src/github.com/nadoo/glider/main.go:84 +0x494
ubnt@ubnt:~$ panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by nadoo** [comment]
Hi @wxyzh , looks like you're compiling glider yourself? have you changed any code of glider? have you tested the binary file from the [release page](https://github.com/nadoo/glider/releases/download/v0.6.2/glider-v0.6.2-linux-mips.zip), does that work?

**Comment by wxyzh** [comment]
@nadoo 未作任何更新，er-x 的cpu是mt7621 mipsle架构，无法运行mips版本。

**Comment by nadoo** [comment]
Accodding to this [change](https://golang.org/doc/go1.10#net/url) , please update to go1.10 to compile the code.

**Comment by wxyzh** [comment]
thanks，works good after update to  go1.10.3
